### ISSUE TITLE
There is no way to run SQL on this system

### ISSUE THREAD

**Issue by dbazza** [halcyon-tech/vscode-ibmi#490]
Hi!

After 0.8.27 upgrade I have the message "There is no way to run SQL on this system" every time I try to expand a node in the object browser. I have downgraded to 0.8.26 but it seems I have the same problem.

What's wrong?

Diego

**Comment by worksofliam** [comment]
@dbazza hi!

Check the connection settings. There is now an 'SQL executor' option, and make sure it's set to db2 or db2util.

**Comment by JamesBrianHill** [comment]
I am also experiencing this issue.

I have tried the following things in an attempt to correct the situation:

1)  Added the following line in the "code-for-ibmi.connectionSettings" section:
"sqlExecutor": "db2"
Then closed VSCode and reconnected.  I still get the message "There is no way to run SQL on this system."

2) Changed the "sqlExecutor" value to "default".  Close VSCode and reconnect.  Still get the error message.

3) Removed this line from the "code-for-ibmi.connectionSettings"  section:
"enableSQL" : true
Then closed VSCode and reconnected.  I still get the message "There is no way to run SQL on this system."

4) Put the "enableSQL": true line back.  Removed my filter and recreated it.  I still get the error message.

What can I do to help debug this?

**Comment by worksofliam** [comment]
Looking into it now.

**Comment by worksofliam** [comment]
@JamesBrianHill Can you confirm `/usr/bin/db2` exists on your system? What about `/QOpenSys/pkgs/bin/db2util`?

**Comment by worksofliam** [comment]
@JamesBrianHill Instead of changing the `settings.json`, considering changing the settings in the Settings window provided by the extension and then giving it another try.

**Comment by JamesBrianHill** [comment]
@worksofliam - yes, /usr/bin/db2 exists.  QOpenSys/pkgs/bin/db2util does not exist.

When I view my extensions in VSCode, select "Code for IBM i" and click on the gear icon and select "Extension Settings", there are 9 options listed:
- Actions (with the option to edit in settings.json)
- Auto Refresh (with a checkbox to enable/disable - currently checked)
- Clear Output Every Time (with a checkbox to enable/disable - currently checked)
- Connections (the only option is to Edit in settings.json)
- Connection Settings (the only option is to Edit in settings.json)
- Grep Ignore Dirs
- Log Compile Output (with a checkbox to enable/disable - currently enabled)
- Show Reconnect Button (with a checkbox to enable/disable - currently disabled)
- Try New Error Parser (with a checkbox to enable/disable - currently disabled)

I do not see any way to edit the sqlExecutor setting other than to edit the settings.json file...

**Comment by worksofliam** [comment]
There is a way to edit the connection settings when connected.

<img width="550" alt="Screenshot 2022-01-31 at 4 52 20 PM" src="https://user-images.githubusercontent.com/3708366/151879382-22c96c70-a175-45c5-9aad-b41c69cc9a3b.png">

**Comment by worksofliam** [comment]
@dbazza @JamesBrianHill I just released 0.8.28 which may solve this. Fingers crossed!

**Comment by JamesBrianHill** [comment]
Ah - thank you for pointing me to the Settings option at the bottom of the editor. I hadn't thought to look there.  I can confirm my "SQL executor" is set to db2 (QSH).

I'm still receiving the same error "There is no way to run SQL on this system."

Once 0.8.28 becomes visible to me, I'll install it and report back here.  Thank you!

**Comment by JamesBrianHill** [comment]
:-(  Unfortunately, the 0.8.28 release did not correct the error for me.

Clicking on the Setting option at the bottom of the editor after connecting to my LPAR, I confirm my "SQL executor" setting is: db2 (QSH).

**Comment by worksofliam** [comment]
@JamesBrianHill any chance you could create a new connection to the same system to see if you get the same issue?

**Comment by worksofliam** [comment]
0.8.29 has just come out and I've made a change to always use `db2` if it's available.

Also, I've added additional logging in case this comes up in the future.

![image](https://user-images.githubusercontent.com/3708366/151900450-a2905d51-9e79-446b-869e-9cbb49fc6108.png)

Please let me know if this release works.

@JamesBrianHill

**Comment by JamesBrianHill** [comment]
@worksofliam - I installed 0.8.29 and continued to see the error.  However, when I deleted that connection entirely and recreated it, everything now works.

I notice that in my settings, SQL executor is now set to None - which makes sense based on your note that the extension will always use db2 if it's available.

If there is anything you'd like me to report on as a postmortem, please let me know.

Thank you very much for your time and effort not only with this particular issue but with your work in general!

**Comment by worksofliam** [comment]
@JamesBrianHill this is a very very odd thing. That usually means it can't find db2 on your system... but you said it exists?

**Comment by worksofliam** [comment]
@JamesBrianHill 

1. Go to the OUTPUT tab, and switch over to Code for IBM i on the dropdown to the right
2. Use the button noted in the image to clear the Code for IBM i  output log
3. Open your connection settings window and change 'SQL executor' to `db2'
4. Either open an unopened source file, or refresh your existing list using the refresh button
5. Did you get an error? It should have added new stuff to the Code for IBM i output log - can you share that here please? 

![Screenshot 2022-02-01 at 9 50 52 AM](https://user-images.githubusercontent.com/3708366/151991184-a2dfabfd-9d98-4413-a93c-3244b5da61dc.png)

**Comment by JamesBrianHill** [comment]
I performed steps 1 - 4. In step 4 I refreshed my existing list using the refresh button.  I did not get an error.  Here is what was added to the output log:

/home/BRHILL: system "DSPFD FILE(HILLB/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/oSwGv7pATx)"
{
    "code": null,
    "signal": null,
    "stdout": "CPF9861: Output file OSWGV7PATX created in library ILEDITOR.\nCPF9862: Member OSWGV7PATX added to output file OSWGV7PATX in library ILEDITOR.\nCPF3030: 28 records added to member OSWGV7PATX in file OSWGV7PATX in ILEDITOR.",
    "stderr": ""
}

/home/BRHILL: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/oSwGv7pATx oSwGv7pATx) TOSTMF('/tmp/vscodetemp-osw8Oc607S') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD) "
{
    "code": null,
    "signal": null,
    "stdout": "CPC2958: All records copied from file OSWGV7PATX in ILEDITOR.",
    "stderr": ""
}

.: rm -f /tmp/vscodetemp-osw8Oc607S
/home/BRHILL: system "DSPFD FILE(HILLB/QSRC) TYPE(*MBR) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/oTbKKH9FUG)"
{
    "code": null,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

{
    "code": null,
    "signal": null,
    "stdout": "CPF9861: Output file OTBKKH9FUG created in library ILEDITOR.\nCPF9862: Member OTBKKH9FUG added to output file OTBKKH9FUG in library ILEDITOR.\nCPF3030: 54 records added to member OTBKKH9FUG in file OTBKKH9FUG in ILEDITOR.",
    "stderr": ""
}

/home/BRHILL: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/oTbKKH9FUG oTbKKH9FUG) TOSTMF('/tmp/vscodetemp-obObxJccks') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD) "
{
    "code": null,
    "signal": null,
    "stdout": "CPC2958: All records copied from file OTBKKH9FUG in ILEDITOR.",
    "stderr": ""
}

.: rm -f /tmp/vscodetemp-obObxJccks
{
    "code": null,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

**Comment by JamesBrianHill** [comment]
Hmmm...  Now I'm getting the "There is no way to run SQL on this system." error again.

I can confirm my SQL executor setting is db2 (QSH)
![image](https://user-images.githubusercontent.com/86387625/151995842-4b0797ec-bf1c-41db-9d1b-80fe57fce060.png)

Here's the output from just connecting to my LPAR:

.: pwd
{
    "code": null,
    "signal": null,
    "stdout": "/home/BRHILL",
    "stderr": ""
}

/home/BRHILL: pwd
{
    "code": null,
    "signal": null,
    "stdout": "/home/BRHILL",
    "stderr": ""
}

/home/BRHILL: echo "liblist" | /QOpenSys/usr/bin/qsh
{
    "code": null,
    "signal": null,
    "stdout": "QSYS        SYS\nQSYS2       SYS\nQHLPSYS     SYS\nQUSRSYS     SYS\nQSHELL      PRD\nQTEMP       USR\nQGDDM       USR\nQGPL        USR\nPCMLIB      USR\nPDPPLIB     USR\nPSYPLIB     USR\nPCIPLIB     USR\nPARPLIB     USR\nPPIPLIB     USR\nPRECOATPRD  USR\nPRECOATDTA  USR\nY2WEB       USR\nY2WEBVENG   USR",
    "stderr": ""
}

/home/BRHILL: system "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2111: Library ILEDITOR already exists."
}

/home/BRHILL: system "CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found."
}

/home/BRHILL: system "CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found."
}

/home/BRHILL: ls -p /QOpenSys/pkgs/bin/
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QOpenSys/pkgs/bin/ not found"
}

After connecting, when I attempt to view the source members in my library, I receive the error.

**Comment by SJLennon** [comment]
Just in case it is useful...  On PUB400.com, DB2 is a SMYLNK, not a PGM.  My SQL Executor is db2util(PASE).
![image](https://user-images.githubusercontent.com/67484051/151995290-9599a0c7-c1ef-43be-af3c-8032863b6c4e.png)
(I really don't know much about DB2.)

**Comment by JamesBrianHill** [comment]
If I change my setting for SQL executor back to None - everything works again!

Here's the output from changing the SQL executor back to None, then reloading VSCode and reconnecting.

.: pwd
{
    "code": null,
    "signal": null,
    "stdout": "/home/BRHILL",
    "stderr": ""
}

/home/BRHILL: pwd
{
    "code": null,
    "signal": null,
    "stdout": "/home/BRHILL",
    "stderr": ""
}

/home/BRHILL: echo "liblist" | /QOpenSys/usr/bin/qsh
{
    "code": null,
    "signal": null,
    "stdout": "QSYS        SYS\nQSYS2       SYS\nQHLPSYS     SYS\nQUSRSYS     SYS\nQSHELL      PRD\nQTEMP       USR\nQGDDM       USR\nQGPL        USR\nPCMLIB      USR\nPDPPLIB     USR\nPSYPLIB     USR\nPCIPLIB     USR\nPARPLIB     USR\nPPIPLIB     USR\nPRECOATPRD  USR\nPRECOATDTA  USR\nY2WEB       USR\nY2WEBVENG   USR",
    "stderr": ""
}

/home/BRHILL: system "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2111: Library ILEDITOR already exists."
}

/home/BRHILL: system "CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found."
}

/home/BRHILL: system "CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found."
}

/home/BRHILL: ls -p /QOpenSys/pkgs/bin/
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QOpenSys/pkgs/bin/ not found"
}

/home/BRHILL: system "DSPFD FILE(HILLB/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/oOslMMEEnl)"
{
    "code": null,
    "signal": null,
    "stdout": "CPF9861: Output file OOSLMMEENL created in library ILEDITOR.\nCPF9862: Member OOSLMMEENL added to output file OOSLMMEENL in library ILEDITOR.\nCPF3030: 28 records added to member OOSLMMEENL in file OOSLMMEENL in ILEDITOR.",
    "stderr": ""
}

/home/BRHILL: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/oOslMMEEnl oOslMMEEnl) TOSTMF('/tmp/vscodetemp-o2ZAQ5LJRm') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD) "
{
    "code": null,
    "signal": null,
    "stdout": "CPC2958: All records copied from file OOSLMMEENL in ILEDITOR.",
    "stderr": ""
}

.: rm -f /tmp/vscodetemp-o2ZAQ5LJRm
{
    "code": null,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

**Comment by JamesBrianHill** [comment]
> 

Thank you SJLennon! It's helpful to get input from different systems.  I am not currently using PUB400.

**Comment by SJLennon** [comment]
Follow up on PUB400 usage.  I changed to db2(QSH), saved the settings, exited VS Code and started again.
Everything seems to work fine for me.
I see output like this, which seems to indicate DB2 is working:
```
/home/LENNONS: echo "/usr/bin/db2 \"
        SELECT
          (b.avgrowsize - 12) as MBMXRL,
          a.iasp_number as MBASP,
          a.table_name AS MBFILE,
          b.system_table_member as MBNAME,
          b.source_type as MBSEU2,
          b.partition_text as MBMTXT
        FROM qsys2.systables AS a
          JOIN qsys2.syspartitionstat AS b
            ON b.table_schema = a.table_schema AND
              b.table_name = a.table_name
        WHERE
          a.table_schema = 'LENNONS1' 
          AND a.table_name = 'USPS_ADR'
          
        ORDER BY
          b.system_table_member
      \"" | /QOpenSys/usr/bin/qsh
```

**Comment by JamesBrianHill** [comment]
More feedback which is probably helpful.  I switched SQL executor back to db2 (QSH) and restarted.  I connected to my LPAR and then cleared the output.  Then I attempted to open my filter to view the source members in my library - and received the error as I expected.  Here's what shows up in my output panel:

/home/BRHILL: system "DSPFD FILE(HILLB/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/oYYYyBZ6HE)"
{
    "code": null,
    "signal": null,
    "stdout": "CPF9861: Output file OYYYYBZ6HE created in library ILEDITOR.\nCPF9862: Member OYYYYBZ6HE added to output file OYYYYBZ6HE in library ILEDITOR.\nCPF3030: 28 records added to member OYYYYBZ6HE in file OYYYYBZ6HE in ILEDITOR.",
    "stderr": ""
}

-------
runSQL()
	Input executor: db2
	Read executor: db2
	Components:
		db2util: undefined
		db2: undefined

Statement:
SELECT * FROM ILEDITOR.oYYYyBZ6HE
-------

**Comment by worksofliam** [comment]
@JamesBrianHill 

Perfect!! That's what I was looking for.

`db2: undefined` indicates that it cannot be found on your system - this is a unique problem for sure. I will look further into this, but I am glad the issue is solved for now.

@SJLennon Thanks for your input here. Glad it is working as expected for you.

**Comment by SJLennon** [comment]
@worksofliam FWIW, again on PUB400.
DB2 seems to have an advantage over db2util.  The SQL below works in iACS and using DB2 in the extension, but returns nothing with db2util.
```
select OBJECT_TYPE ,PATH_NAME ,OBJECT_OWNER
 FROM TABLE (QSYS2.IFS_OBJECT_STATISTICS(
START_PATH_NAME => '/tmp',
SUBTREE_DIRECTORIES => 'YES'))
WHERE last_used_timestamp is null  and object_type <> '*DIR'
```
I suspect it has to do with SQL returning warnings. I logged an issue back in December with the db2util project:
https://github.com/IBM/ibmi-db2util/issues/21

**Comment by worksofliam** [comment]
(Also, us all working together here is one of the reasons I love open-source!)

**Comment by ThePrez** [comment]
Does the `QSYS.QZDFMDB2` *PGM object exist?

**Comment by JamesBrianHill** [comment]
Just a follow up to SJLennon's note about PUB400.com - when I put an 8 next to my /usr/bin/db2 to "Display Attributes", it tells me my /usr/bin/db2 is of Type: SYMLNK.
![image](https://user-images.githubusercontent.com/86387625/152004527-51bea340-19d1-461b-a0f0-87348a131a64.png)

At first I thought having a CCSID of 13488 was odd but Google (and IBM's website) tell me that CCSID is an IBM-specific version of UTF-16. That seems fine to me.

@ThePrez  - I can confirm that QSYS/QZDFMDB2 exists on the LPAR I am connected to (which is not PUB400).
![image](https://user-images.githubusercontent.com/86387625/152005462-c1377922-3647-49bb-99b2-1293f40a9f45.png)

**Comment by worksofliam** [comment]
New SQL executor: 

```
echo "select * from sample.employee" | LC_ALL=en_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-i' '-S')"
```

**Comment by worksofliam** [comment]
Hi @dbazza 

What's the status here for you?

**Comment by dbazza** [comment]
Current version works for and issue is solved!

Thanks,
Diego

Il giorno mar 1 feb 2022 alle ore 22:00 barry ***@***.***> ha
scritto:
